/**
 * MemoryConsolidator — orchestration of the consolidation pipeline
 * (narrative director, Task 8).
 *
 * Extracted from Task 6's inline NarrativeDirectorService.consolidatePending()
 * pipeline: truncates events to `max_events_per_call` (keeping the last N),
 * calls the MemoryConsolidatorPort, validates the returned ops through the
 * Task 5 validators plus the C8 §6.2 identity validators (explicit
 * ValidatedProposal / IdentityValidationIssue results — no silent tag
 * filtering), and generates the episode id (`ep_{revision+1}_{fromSeq}`).
 */

import type { NarrativeConfig } from "../../config.js";
import type { DiagnosticSink } from "../../core/ports/diagnostic-sink.js";
import { silentDiagnosticSink } from "../../core/ports/diagnostic-sink.js";
import type { StoredEvent } from "../../schema.js";
import { projectMemoryEvidence } from "../../story/event-projection.js";
import type { ProjectedEvent } from "../../story/event-projection.js";
import type { CharacterRegistry } from "../../core/characters/types.js";
import type {
  NarrativeMemoryState,
  PlotThread,
  SetupPayoff,
  EpisodeMemory,
} from "../../core/narrative/memory-types.js";
import type {
  ThreadOp,
  SetupOp,
  EpisodeSummaryOp,
  FactOp,
  BeliefOp,
  AuditFinding,
  RejectedOp,
  IdentityValidationIssue,
  ValidatedProposal,
} from "../../core/narrative/memory-operation.js";
import {
  validateThreadOp,
  validateSetupOp,
  validateEpisodeOp,
  validateFactOp,
  validateBeliefOp,
  validateFinding,
  validateCharacterTags,
  validateEvidenceRefs,
  validateReferenceTags,
  acceptedProposal,
  rejectedProposal,
  formatIdentityIssues,
  buildMemoryIdentityView,
  applyThreadOpToState,
  applySetupOpToState,
  applyFactOpToState,
  applyBeliefOpToState,
  rejectionRule,
  MAX_ESTABLISH_PER_BATCH,
  MAX_BELIEF_OPS_PER_CHARACTER_PER_BATCH,
  MAX_FINDINGS_PER_BATCH,
} from "./memory-validator.js";
import type { MemoryIdentityView } from "./memory-validator.js";

// ---------------------------------------------------------------------------
// Consolidator port (defined in Task 6; implemented here)
// ---------------------------------------------------------------------------

export interface ConsolidationRequest {
  events: StoredEvent[];
  threads: PlotThread[];
  setups: SetupPayoff[];
  stateLocation: string;
  stateCharacters: string[];
  /**
   * C8 §6.2 身份视图（main：请求侧携带——campus 由 adapter 构造后随
   * ConsolidationResult 回传，main 按计划 §6.2「main 请求必须携带…允许
   * 角色及 evidence 范围」在请求上显式携带）。MemoryConsolidator 在
   * registry 在场时构造；adapter 用同一视图渲染权威 ID 段，校验与模型
   * 被告知的权威同源。缺席 = legacy（无 registry）。
   *
   * M2 扩展点：同一视图上扩展 fact/belief 引用集与 belief 获知来源。
   */
  identity?: MemoryIdentityView;
  /**
   * C8 §6.2 记忆证据投影（身份稳定事件视图，§5.1 的 projectMemoryEvidence
   * 输出）。请求侧携带：adapter 直接渲染，不再各自投影（与 identity 同
   * 生共死——两者都由本批 events + 同一 registry 派生）。缺席 = legacy。
   */
  evidenceEvents?: readonly ProjectedEvent[];
}

export interface ConsolidationResult {
  episode: EpisodeSummaryOp;
  threadOps: ThreadOp[];
  setupOps: SetupOp[];
  /** MA-B 扩展（§4）：facts/beliefs/findings 搭载同一 consolidator 调用。 */
  factOps: FactOp[];
  beliefOps: BeliefOp[];
  findings: AuditFinding[];
}

export interface MemoryConsolidatorPort {
  consolidate(request: ConsolidationRequest): Promise<ConsolidationResult>;
}

/** Outcome of one consolidation pass (Task 8). */
export interface ConsolidationOutcome {
  /** Raw consolidator result; null when the consolidator failed. */
  result: ConsolidationResult | null;
  /** Validated episode (id generated by this class); null when rejected. */
  episode: EpisodeMemory | null;
  /**
   * §6.2 episode proposal verdict: accepted（value + 空 issues，含合法空
   * 提案 no-op）/ rejected（IdentityValidationIssue[]，字段路径 + 违规值）。
   * undefined = 本次没有待校验提案（port 缺席/失败/无事件）。形状类拒绝
   * （如 summary 超长）不属于身份维度：status 为 rejected 但 issues 为空，
   * 原因见 rejected[].reason。
   */
  episodeProposal: ValidatedProposal<EpisodeMemory> | undefined;
  /** Thread ops that passed validation. */
  threadOps: ThreadOp[];
  /** Setup ops that passed validation. */
  setupOps: SetupOp[];
  /** MA-B：通过校验的 facts/beliefs/findings（预算与逐条校验后）。 */
  factOps: FactOp[];
  beliefOps: BeliefOp[];
  findings: AuditFinding[];
  /** Ops rejected by the validators (Task 5 rules + C8 identity issues). */
  rejected: RejectedOp[];
  /** 本次全部 §6.2 身份/引用问题（episode + ops，按拒绝记录顺序）。 */
  identityIssues: readonly IdentityValidationIssue[];
  /** identity = 提案携带身份视图并按 §6.2 校验；legacy = 无身份权威。 */
  validationMode: "identity" | "legacy";
}

// ---------------------------------------------------------------------------
// Constants (moved from narrative-director-service.ts)
// ---------------------------------------------------------------------------

/** Thread statuses that count as "active" for brief and consolidation. */
export const ACTIVE_THREAD_STATUSES: ReadonlySet<PlotThread["status"]> = new Set([
  "open",
  "developing",
  "ready_to_resolve",
]);

/** Setup statuses that are non-terminal (still relevant). */
export const NON_TERMINAL_SETUP_STATUSES: ReadonlySet<SetupPayoff["status"]> = new Set([
  "planned",
  "seeded",
  "reinforced",
  "ready",
]);

// ---------------------------------------------------------------------------
// MemoryConsolidator
// ---------------------------------------------------------------------------

export class MemoryConsolidator {
  private readonly port: MemoryConsolidatorPort | undefined;
  private readonly config: NarrativeConfig;
  private readonly diagnostics: DiagnosticSink;
  /**
   * C2/C8 角色注册表（bootstrap 经 NarrativeDirectorService 注入）。
   * 在场时请求侧构造 §6.2 身份视图（main 接线）；缺席 = legacy。
   */
  private readonly registry: CharacterRegistry | undefined;

  constructor(opts: {
    port: MemoryConsolidatorPort | undefined;
    config: NarrativeConfig;
    /** C8 §6.2：registry 在场时请求携带身份视图与证据投影。 */
    registry?: CharacterRegistry;
    diagnostics?: DiagnosticSink;
  }) {
    this.port = opts.port;
    this.config = opts.config;
    this.registry = opts.registry;
    this.diagnostics = opts.diagnostics ?? silentDiagnosticSink;
  }

  /**
   * Run one consolidation pass: cap events, call the port, filter ops
   * through the validators, generate the episode id.
   *
   * - Events are capped to `max_events_per_call`, keeping the LAST N.
   * - A port failure (or an absent port) yields an empty outcome with
   *   `result: null` — never throws.
   */
  async consolidate(
    events: StoredEvent[],
    memory: NarrativeMemoryState,
    stateLocation: string,
    stateCharacters: string[],
  ): Promise<ConsolidationOutcome> {
    // No port → empty outcome, nothing called
    if (this.port === undefined) {
      return emptyOutcome();
    }

    if (events.length === 0) {
      return emptyOutcome();
    }

    // Cap events to max_events_per_call (keep the OLDEST N, FIFO — same
    // order the director batches in; this cap is defense in depth).
    const maxEvents = this.config.consolidation.max_events_per_call;
    let batch: StoredEvent[];
    if (events.length > maxEvents) {
      this.diagnostics.info(
        "NarrativeDirector",
        `Dropping ${events.length - maxEvents} newer overflow events from batch (max ${maxEvents})`,
      );
      batch = events.slice(0, maxEvents);
    } else {
      batch = events;
    }

    const fromSeq = batch[0]!.seq;

    // Active threads and non-terminal setups for the consolidator
    const activeThreads = Object.values(memory.threads).filter((t) =>
      ACTIVE_THREAD_STATUSES.has(t.status),
    );
    const nonTerminalSetups = Object.values(memory.setups).filter((s) =>
      NON_TERMINAL_SETUP_STATUSES.has(s.status),
    );

    // --- C8 §6.2 request-side identity view（main 接线）---
    // registry 在场时构造身份视图与记忆证据投影，随 REQUEST 显式携带
    // （计划 §6.2「main 请求必须携带…允许角色及 evidence 范围」；campus
    // 是 adapter 构造后随 ConsolidationResult 回传——校验函数零差异）。
    // adapter 用同一视图渲染权威 ID 段：校验与模型被告知的权威同源。
    // registry 缺席 = legacy：请求不携带，标签不校验身份维度。
    const evidence =
      this.registry !== undefined
        ? projectMemoryEvidence(batch, this.registry)
        : undefined;
    const identity =
      this.registry !== undefined && evidence !== undefined
        ? buildMemoryIdentityView({
            events: batch,
            registry: this.registry,
            stateCharacters,
            stateLocation,
            evidence,
          })
        : undefined;

    // --- Call consolidator (failure → null result, never throws) ---
    let result: ConsolidationResult;
    try {
      result = await this.port.consolidate({
        events: batch,
        threads: activeThreads,
        setups: nonTerminalSetups,
        stateLocation,
        stateCharacters,
        ...(identity !== undefined ? { identity } : {}),
        ...(evidence !== undefined ? { evidenceEvents: evidence } : {}),
      });
    } catch (err) {
      this.diagnostics.warn(
        "NarrativeDirector",
        `consolidation failed: ${String(err)}`,
      );
      return emptyOutcome();
    }

    // --- Filter through the validators transactionally ---
    // Ops are validated in OUTPUT order against a SHADOW copy of the
    // memory: each accepted op is applied to the shadow before the next
    // one is validated, so budgets and state transitions see the ops that
    // came before them in the same batch (two creates against a full
    // budget, seed-then-reinforce, repeated advances...). A rejected op is
    // NOT applied to the shadow. (Audit finding 4.)
    //
    // C8 §6.2: identity/reference validation is explicit. The episode
    // proposal verdict is a ValidatedProposal (accepted — including legal
    // empty proposals — or rejected with code/path/value issues); ops
    // carry structured issues on RejectedOp. There is NO silent tag
    // filtering anywhere (filterCanonicalTags is gone): an illegal tag
    // rejects the whole episode proposal instead of being dropped.
    const view = identity;
    const validationMode: "identity" | "legacy" =
      view !== undefined ? "identity" : "legacy";

    const rejected: RejectedOp[] = [];
    const shadow = structuredClone(memory);
    const batchLastSeq = batch[batch.length - 1]!.seq;

    // Reference authorities for episode tags: exactly the lists rendered
    // into the request (active threads / non-terminal setups), plus thread
    // ids created by same-batch accepted create ops.
    const knownThreadIds = new Set(activeThreads.map((t) => t.id));
    const knownSetupIds = new Set(nonTerminalSetups.map((s) => s.id));

    // 1) Thread ops (existing Task 5 rules; no identity fields on thread ops).
    //    Rejections buffered locally so the Task 6 recording order stays
    //    episode → thread → setup (the episode is validated in step 3 but
    //    must be recorded first).
    const threadRejected: RejectedOp[] = [];
    const threadOps: ThreadOp[] = [];
    for (const op of result.threadOps) {
      const reason = validateThreadOp(op, shadow, this.config);
      if (reason === null) {
        threadOps.push(op);
        if (op.type === "create") {
          knownThreadIds.add(op.id);
        }
        applyThreadOpToState(shadow, op, 0); // checkpoint irrelevant for validation
      } else {
        threadRejected.push({ kind: "thread", op, reason, rule: rejectionRule(reason) });
      }
    }

    // 2) Setup ops: Task 5 rules + §6.2 evidence refs. An op with illegal
    //    evidence is rejected as a whole (its issues are reported, never
    //    silently stripped).
    const setupRejected: RejectedOp[] = [];
    const setupEvidenceIssues: IdentityValidationIssue[] = [];
    const setupOps: SetupOp[] = [];
    result.setupOps.forEach((op, index) => {
      const evidenceIssues =
        view !== undefined
          ? validateEvidenceRefs(
              op.evidenceEventIds ?? [],
              view,
              `setupOps[${index}].evidenceEventIds`,
            )
          : [];
      const reason = validateSetupOp(op, shadow, this.config, batchLastSeq);
      if (reason === null && evidenceIssues.length === 0) {
        setupOps.push(op);
        applySetupOpToState(shadow, op, 0); // checkpoint irrelevant for validation
      } else {
        setupEvidenceIssues.push(...evidenceIssues);
        setupRejected.push({
          kind: "setup",
          op,
          reason:
            reason ??
            `证据事件引用非法（见 issues：${formatIdentityIssues(evidenceIssues, view)}）`,
          ...(reason !== null ? { rule: rejectionRule(reason) } : {}),
          ...(evidenceIssues.length > 0 ? { issues: evidenceIssues } : {}),
        });
      }
    });

    // 3) Episode proposal: shape rules + §6.2 identity/reference tags.
    //    ALL issues are collected (never stops at the first) and reported
    //    together with field paths and offending values.
    const shapeReason = validateEpisodeOp(result.episode);
    const episodeIssues: IdentityValidationIssue[] = [];
    if (view !== undefined) {
      episodeIssues.push(
        ...validateCharacterTags(
          result.episode.characters,
          view,
          "episode.characters",
        ),
        ...validateReferenceTags(
          result.episode.locations,
          view.canonicalLocations,
          "episode.locations",
        ),
      );
    }
    episodeIssues.push(
      ...validateReferenceTags(result.episode.threads, knownThreadIds, "episode.threads"),
      ...validateReferenceTags(result.episode.setups, knownSetupIds, "episode.setups"),
    );

    let episode: EpisodeMemory | null = null;
    let episodeProposal: ValidatedProposal<EpisodeMemory> | undefined;
    if (shapeReason !== null || episodeIssues.length > 0) {
      episodeProposal = rejectedProposal(episodeIssues);
      rejected.push({
        kind: "episode",
        op: result.episode,
        reason:
          shapeReason ??
          `episode 提案身份/引用非法（§6.2）：${formatIdentityIssues(episodeIssues, view)}`,
        ...(shapeReason !== null ? { rule: rejectionRule(shapeReason) } : {}),
        ...(episodeIssues.length > 0 ? { issues: episodeIssues } : {}),
      });
    } else {
      episode = {
        id: `ep_${memory.revision + 1}_${fromSeq}`,
        fromEventSeq: fromSeq,
        toEventSeq: batchLastSeq,
        summary: result.episode.summary,
        characters: result.episode.characters,
        locations: result.episode.locations,
        threads: result.episode.threads,
        setups: result.episode.setups,
        importance: result.episode.importance,
      };
      // 合法提案（含合法空提案 = no-op）：value + 空 issues。
      episodeProposal = acceptedProposal(episode);
    }

    // Rejection recording order stays episode → thread → setup →
    // fact → belief → finding (Task 6 + MA-B).
    rejected.push(...threadRejected, ...setupRejected);

    // 4) MA-B fact/belief/finding filters（M2 将在同一身份视图上扩展
    //    fact/belief 引用集与 belief 获知来源——本层只做共享身份校验）。
    const factOps = this.filterFactOps(
      result,
      shadow,
      memory.revision + 1,
      batchLastSeq,
      rejected,
    );
    const beliefOps = this.filterBeliefOps(
      result,
      shadow,
      stateCharacters,
      memory.revision + 1,
      batchLastSeq,
      rejected,
    );
    const findings = this.collectFindings(result, batchLastSeq, rejected);

    // §6.2 身份/引用问题聚合（episode + setupOps 证据；fact/belief 的
    // 引用/获知校验属 M2，届时并入本列表）。
    const identityIssues: readonly IdentityValidationIssue[] = [
      ...episodeIssues,
      ...setupEvidenceIssues,
    ];

    return {
      result,
      episode,
      episodeProposal,
      threadOps,
      setupOps,
      factOps,
      beliefOps,
      findings,
      rejected,
      identityIssues,
      validationMode,
    };
  }

  // -------------------------------------------------------------------------
  // Per-op-class validation filters (transactional against `shadow`)
  // -------------------------------------------------------------------------

  private filterFactOps(
    result: ConsolidationResult,
    shadow: NarrativeMemoryState,
    idRevision: number,
    batchLastSeq: number,
    rejected: RejectedOp[],
  ): FactOp[] {
    const accepted: FactOp[] = [];
    let establishCount = 0;
    let factSeq = 0;
    for (const op of result.factOps) {
      const reason = validateFactOp(op, shadow.facts, batchLastSeq);
      if (reason !== null) {
        rejected.push({ kind: "fact", op, reason, rule: rejectionRule(reason) });
        continue;
      }
      if (op.type === "establish") {
        if (establishCount >= MAX_ESTABLISH_PER_BATCH) {
          rejected.push({
            kind: "fact",
            op,
            reason: "[FACT_BUDGET_EXCEEDED] 每批 establish 上限 3",
            rule: "FACT_BUDGET_EXCEEDED",
          });
          continue;
        }
        establishCount += 1;
      }
      // 影子应用：amend 在影子中标 superseded，供后续 op 校验看到（事务性）。
      applyFactOpToState(shadow, op, factId(idRevision, ++factSeq), 0);
      accepted.push(op);
    }
    return accepted;
  }

  private filterBeliefOps(
    result: ConsolidationResult,
    shadow: NarrativeMemoryState,
    stateCharacters: readonly string[],
    idRevision: number,
    batchLastSeq: number,
    rejected: RejectedOp[],
  ): BeliefOp[] {
    const accepted: BeliefOp[] = [];
    let beliefSeq = 0;
    const perCharacterOps = new Map<string, number>();
    for (const op of result.beliefOps) {
      const reason = validateBeliefOp(op, shadow.beliefs, stateCharacters, batchLastSeq);
      if (reason !== null) {
        rejected.push({ kind: "belief", op, reason, rule: rejectionRule(reason) });
        continue;
      }
      const count = perCharacterOps.get(op.characterId) ?? 0;
      if (count >= MAX_BELIEF_OPS_PER_CHARACTER_PER_BATCH) {
        rejected.push({
          kind: "belief",
          op,
          reason: "[BELIEF_BUDGET_EXCEEDED] 每角色每批 belief op 上限 2",
          rule: "BELIEF_BUDGET_EXCEEDED",
        });
        continue;
      }
      if (op.type !== "correct") {
        // 每角色 active 上限（§6.1：超限拒新保旧）。
        const activeCount = shadow.beliefs.filter(
          (b) => b.characterId === op.characterId && b.status === "active",
        ).length;
        if (activeCount >= this.config.beliefs.max_active_per_character) {
          rejected.push({
            kind: "belief",
            op,
            reason: "[BELIEF_BUDGET_EXCEEDED] 角色 active beliefs 已达上限",
            rule: "BELIEF_BUDGET_EXCEEDED",
          });
          continue;
        }
      }
      perCharacterOps.set(op.characterId, count + 1);
      applyBeliefOpToState(shadow, op, beliefId(idRevision, ++beliefSeq), 0);
      accepted.push(op);
    }
    return accepted;
  }

  /** findings 不修改记忆状态：逐条校验 + 批量上限（§9.2）。 */
  private collectFindings(
    result: ConsolidationResult,
    batchLastSeq: number,
    rejected: RejectedOp[],
  ): AuditFinding[] {
    const accepted: AuditFinding[] = [];
    if (result.findings.length > MAX_FINDINGS_PER_BATCH) {
      rejected.push({
        kind: "finding",
        op: result.findings,
        reason: "[FINDING_BATCH_EXCEEDED] 每批 findings 上限 5",
        rule: "FINDING_BATCH_EXCEEDED",
      });
    }
    for (const finding of result.findings.slice(0, MAX_FINDINGS_PER_BATCH)) {
      const reason = validateFinding(finding, batchLastSeq);
      if (reason === null) {
        accepted.push(finding);
      } else {
        rejected.push({ kind: "finding", op: finding, reason, rule: rejectionRule(reason) });
      }
    }
    return accepted;
  }
}

/** 确定性 fact id（revision 派生，重放幂等——与 episode id 同一纪律）。
 * 服务端应用时必须用同一公式重新生成（shadow 校验与应用分离）。 */
export function factId(revision: number, seq: number): string {
  return `fact_${revision}_${seq}`;
}

/** 确定性 belief id。 */
export function beliefId(revision: number, seq: number): string {
  return `belief_${revision}_${seq}`;
}

function emptyOutcome(): ConsolidationOutcome {
  return {
    result: null,
    episode: null,
    episodeProposal: undefined,
    threadOps: [],
    setupOps: [],
    factOps: [],
    beliefOps: [],
    findings: [],
    rejected: [],
    identityIssues: [],
    // 无提案可校验（port 缺席/失败/空批次）：没有身份权威参与。
    validationMode: "legacy",
  };
}
