/**
 * MemoryConsolidator — orchestration of the consolidation pipeline
 * (narrative director, Task 8).
 *
 * Extracted from Task 6's inline NarrativeDirectorService.consolidatePending()
 * pipeline: truncates events to `max_events_per_call` (keeping the last N),
 * calls the MemoryConsolidatorPort, filters the returned ops through the
 * Task 5 validators, and generates the episode id (`ep_{revision+1}_{fromSeq}`).
 * Behavior is identical to the Task 6 inline pipeline: same validator rules,
 * same rejection recording, same diagnostics.
 */

import type { NarrativeConfig } from "../../config.js";
import type { DiagnosticSink } from "../../core/ports/diagnostic-sink.js";
import { silentDiagnosticSink } from "../../core/ports/diagnostic-sink.js";
import type { StoredEvent } from "../../schema.js";
import type {
  NarrativeMemoryState,
  PlotThread,
  SetupPayoff,
  EpisodeMemory,
} from "../../core/narrative/memory-types.js";
import type {
  ThreadOp,
  SetupOp,
  EpisodeSummaryOp,
  RejectedOp,
} from "../../core/narrative/memory-operation.js";
import {
  validateThreadOp,
  validateSetupOp,
  validateEpisodeOp,
  applyThreadOpToState,
  applySetupOpToState,
} from "./memory-validator.js";

// ---------------------------------------------------------------------------
// Consolidator port (defined in Task 6; implemented here)
// ---------------------------------------------------------------------------

export interface ConsolidationRequest {
  events: StoredEvent[];
  threads: PlotThread[];
  setups: SetupPayoff[];
  stateLocation: string;
  stateCharacters: string[];
}

export interface ConsolidationResult {
  episode: EpisodeSummaryOp;
  threadOps: ThreadOp[];
  setupOps: SetupOp[];
}

export interface MemoryConsolidatorPort {
  consolidate(request: ConsolidationRequest): Promise<ConsolidationResult>;
}

/** Outcome of one consolidation pass (Task 8). */
export interface ConsolidationOutcome {
  /** Raw consolidator result; null when the consolidator failed. */
  result: ConsolidationResult | null;
  /** Validated episode (id generated by this class); null when rejected. */
  episode: EpisodeMemory | null;
  /** Thread ops that passed validation. */
  threadOps: ThreadOp[];
  /** Setup ops that passed validation. */
  setupOps: SetupOp[];
  /** Ops rejected by the validators (Task 5 rules). */
  rejected: RejectedOp[];
}

// ---------------------------------------------------------------------------
// Constants (moved from narrative-director-service.ts)
// ---------------------------------------------------------------------------

/** Thread statuses that count as "active" for brief and consolidation. */
export const ACTIVE_THREAD_STATUSES: ReadonlySet<PlotThread["status"]> = new Set([
  "open",
  "developing",
  "ready_to_resolve",
]);

/** Setup statuses that are non-terminal (still relevant). */
export const NON_TERMINAL_SETUP_STATUSES: ReadonlySet<SetupPayoff["status"]> = new Set([
  "planned",
  "seeded",
  "reinforced",
  "ready",
]);

// ---------------------------------------------------------------------------
// MemoryConsolidator
// ---------------------------------------------------------------------------

export class MemoryConsolidator {
  private readonly port: MemoryConsolidatorPort | undefined;
  private readonly config: NarrativeConfig;
  private readonly diagnostics: DiagnosticSink;

  constructor(opts: {
    port: MemoryConsolidatorPort | undefined;
    config: NarrativeConfig;
    diagnostics?: DiagnosticSink;
  }) {
    this.port = opts.port;
    this.config = opts.config;
    this.diagnostics = opts.diagnostics ?? silentDiagnosticSink;
  }

  /**
   * Run one consolidation pass: cap events, call the port, filter ops
   * through the validators, generate the episode id.
   *
   * - Events are capped to `max_events_per_call`, keeping the LAST N.
   * - A port failure (or an absent port) yields an empty outcome with
   *   `result: null` — never throws.
   */
  async consolidate(
    events: StoredEvent[],
    memory: NarrativeMemoryState,
    stateLocation: string,
    stateCharacters: string[],
  ): Promise<ConsolidationOutcome> {
    // No port → empty outcome, nothing called
    if (this.port === undefined) {
      return emptyOutcome();
    }

    if (events.length === 0) {
      return emptyOutcome();
    }

    // Cap events to max_events_per_call (keep the OLDEST N, FIFO — same
    // order the director batches in; this cap is defense in depth).
    const maxEvents = this.config.consolidation.max_events_per_call;
    let batch: StoredEvent[];
    if (events.length > maxEvents) {
      this.diagnostics.info(
        "NarrativeDirector",
        `Dropping ${events.length - maxEvents} newer overflow events from batch (max ${maxEvents})`,
      );
      batch = events.slice(0, maxEvents);
    } else {
      batch = events;
    }

    const fromSeq = batch[0]!.seq;

    // Active threads and non-terminal setups for the consolidator
    const activeThreads = Object.values(memory.threads).filter((t) =>
      ACTIVE_THREAD_STATUSES.has(t.status),
    );
    const nonTerminalSetups = Object.values(memory.setups).filter((s) =>
      NON_TERMINAL_SETUP_STATUSES.has(s.status),
    );

    // --- Call consolidator (failure → null result, never throws) ---
    let result: ConsolidationResult;
    try {
      result = await this.port.consolidate({
        events: batch,
        threads: activeThreads,
        setups: nonTerminalSetups,
        stateLocation,
        stateCharacters,
      });
    } catch (err) {
      this.diagnostics.warn(
        "NarrativeDirector",
        `consolidation failed: ${String(err)}`,
      );
      return emptyOutcome();
    }

    // --- Filter through the validators transactionally ---
    // Ops are validated in OUTPUT order against a SHADOW copy of the
    // memory: each accepted op is applied to the shadow before the next
    // one is validated, so budgets and state transitions see the ops that
    // came before them in the same batch (two creates against a full
    // budget, seed-then-reinforce, repeated advances...). A rejected op is
    // NOT applied to the shadow. (Audit finding 4.)
    const rejected: RejectedOp[] = [];
    const threadOps: ThreadOp[] = [];
    const setupOps: SetupOp[] = [];
    const shadow = structuredClone(memory);

    let episode: EpisodeMemory | null = null;
    const epReason = validateEpisodeOp(result.episode);
    if (epReason === null) {
      episode = {
        id: `ep_${memory.revision + 1}_${fromSeq}`,
        fromEventSeq: fromSeq,
        toEventSeq: batch[batch.length - 1]!.seq,
        summary: result.episode.summary,
        characters: result.episode.characters,
        locations: result.episode.locations,
        threads: result.episode.threads,
        setups: result.episode.setups,
        importance: result.episode.importance,
      };
    } else {
      rejected.push({ kind: "episode", op: result.episode, reason: epReason });
    }

    for (const op of result.threadOps) {
      const reason = validateThreadOp(op, shadow, this.config);
      if (reason === null) {
        threadOps.push(op);
        applyThreadOpToState(shadow, op, 0); // checkpoint irrelevant for validation
      } else {
        rejected.push({ kind: "thread", op, reason });
      }
    }

    for (const op of result.setupOps) {
      const reason = validateSetupOp(op, shadow, this.config, batch[batch.length - 1]!.seq);
      if (reason === null) {
        setupOps.push(op);
        applySetupOpToState(shadow, op, 0); // checkpoint irrelevant for validation
      } else {
        rejected.push({ kind: "setup", op, reason });
      }
    }

    return { result, episode, threadOps, setupOps, rejected };
  }
}

function emptyOutcome(): ConsolidationOutcome {
  return {
    result: null,
    episode: null,
    threadOps: [],
    setupOps: [],
    rejected: [],
  };
}
