/**
 * RuntimeClient — the browser's connection layer for the Runtime WebSocket
 * (design doc §9.1).
 *
 * Responsibilities: establish and restore the socket, send RuntimeCommands,
 * receive ServerMessages (RuntimeOutput / AudioDescriptor / projection),
 * validate inbound wire messages, maintain the monotonic sequence for de-dup,
 * and re-send `client.ready` after every (re)connect. It never touches the
 * DOM, TTS, or IndexedDB.
 *
 * This module imports ONLY `@shared/wire`, DOM, and sibling runtime modules.
 * The RuntimeCommand union lives in core; the wire schemas encode its shape,
 * so the browser works with the z.infer'd wire form instead.
 */
import { RuntimeCommandSchema, ServerMessageSchema } from "@shared/wire/schemas.js";
import type { ClientMessage } from "@shared/wire/client-message.js";
import type { ServerMessage } from "@shared/wire/server-message.js";
import type { z } from "zod";

/** RuntimeCommand wire form (the command union is defined in core). */
export type RuntimeCommandWire = z.infer<typeof RuntimeCommandSchema>;

export type ConnectionState = "connecting" | "open" | "closed";

/**
 * Minimal structural WebSocket surface the client depends on. Browsers pass
 * `globalThis.WebSocket`; tests inject a fake via `webSocketImpl`.
 */
export interface WebSocketLike {
  send(data: string): void;
  close(code?: number, reason?: string): void;
  onopen: ((ev: Event) => unknown) | null;
  onmessage: ((ev: MessageEvent) => unknown) | null;
  onclose: ((ev: CloseEvent) => unknown) | null;
  onerror: ((ev: Event) => unknown) | null;
  readyState: number;
}

export type WebSocketCtor = new (url: string) => WebSocketLike;

export interface RuntimeClientOptions {
  /** e.g. `ws://127.0.0.1:port/ws/runtime`; the session token is appended. */
  wsUrl: string;
  /** Local Session Token (§8.3), sent as the `token` query parameter. */
  token: string;
  /** Every validated ServerMessage is forwarded here (after de-dup). */
  onServerMessage(msg: ServerMessage): void;
  onConnectionChange(state: ConnectionState): void;
  /** Test seam; defaults to `globalThis.WebSocket`. */
  webSocketImpl?: WebSocketCtor;
}

const INITIAL_BACKOFF_MS = 500;
const MAX_BACKOFF_MS = 8_000;

export class RuntimeClient {
  private readonly options: RuntimeClientOptions;
  private readonly webSocketImpl: WebSocketCtor | undefined;
  private ws: WebSocketLike | null = null;
  private state: ConnectionState | "idle" = "idle";
  /** Monotonic sequence watermark for `runtime.output` de-dup (§9.1). */
  private lastSeenSequence = -1;
  private backoffMs = INITIAL_BACKOFF_MS;
  private retryTimer: ReturnType<typeof setTimeout> | null = null;
  private manuallyClosed = false;
  private connectPromise: Promise<void> | null = null;
  private resolveConnect: (() => void) | null = null;

  constructor(options: RuntimeClientOptions) {
    this.options = options;
    this.webSocketImpl =
      options.webSocketImpl ??
      (globalThis.WebSocket as unknown as WebSocketCtor | undefined);
  }

  /** Opens the WebSocket; resolves once the connection is open and `client.ready` was sent. */
  connect(): Promise<void> {
    if (this.state === "open") return Promise.resolve();
    if (this.connectPromise === null) {
      this.connectPromise = new Promise<void>((resolve) => {
        this.resolveConnect = resolve;
      });
      this.manuallyClosed = false;
      if (this.retryTimer === null && this.ws === null) {
        this.openSocket();
      }
    }
    return this.connectPromise;
  }

  /** Send a runtime command; the `commandId` is generated by the UI layer. */
  sendCommand(commandId: string, command: RuntimeCommandWire): void {
    this.send({ type: "runtime.command", commandId, command });
  }

  /** Raw send for reports (e.g. audio cache/buffer reports). */
  send(msg: ClientMessage): void {
    if (this.state !== "open" || this.ws === null) {
      console.warn("RuntimeClient: dropping message while not connected", msg.type);
      return;
    }
    this.ws.send(JSON.stringify(msg));
  }

  /** Shuts the connection down; no further reconnect attempts. */
  close(): void {
    this.manuallyClosed = true;
    if (this.retryTimer !== null) {
      clearTimeout(this.retryTimer);
      this.retryTimer = null;
    }
    const ws = this.ws;
    this.ws = null;
    if (ws !== null) {
      // Detach handlers first so the fake/browser close event cannot reschedule.
      ws.onopen = null;
      ws.onmessage = null;
      ws.onclose = null;
      ws.onerror = null;
      try {
        ws.close();
      } catch {
        // Already closed; nothing to do.
      }
    }
    if (this.state !== "closed") {
      this.setConnectionState("closed");
    }
    this.settleConnect();
  }

  private openSocket(): void {
    if (this.ws !== null) return; // Already an attempt in flight.
    if (this.webSocketImpl === undefined) {
      throw new Error(
        "RuntimeClient: no WebSocket implementation available (pass webSocketImpl outside the browser)",
      );
    }
    const url = new URL(this.options.wsUrl);
    url.searchParams.set("token", this.options.token);
    const ws = new this.webSocketImpl(url.toString());
    this.ws = ws;
    this.setConnectionState("connecting");
    ws.onopen = () => this.handleOpen(ws);
    ws.onmessage = (ev) => this.handleMessage(ev, ws);
    ws.onclose = () => this.handleClose(ws);
    ws.onerror = () => {
      // The close event follows and drives lifecycle/reconnect.
    };
  }

  private handleOpen(ws: WebSocketLike): void {
    if (this.ws !== ws) return; // Stale socket.
    this.setConnectionState("open");
    this.backoffMs = INITIAL_BACKOFF_MS;
    ws.send(JSON.stringify(this.readyMessage()));
    this.settleConnect();
  }

  private handleMessage(ev: MessageEvent, ws: WebSocketLike): void {
    if (this.ws !== ws) return;
    const raw = ev.data;
    if (typeof raw !== "string") {
      console.warn("RuntimeClient: dropped non-string message", raw);
      return;
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (err) {
      console.warn("RuntimeClient: dropped unparseable message", err);
      return;
    }
    const result = ServerMessageSchema.safeParse(parsed);
    if (!result.success) {
      console.warn("RuntimeClient: dropped invalid server message", result.error);
      return;
    }
    const msg = result.data as ServerMessage;
    if (msg.type === "runtime.output") {
      if (msg.sequence <= this.lastSeenSequence) return; // Duplicate/stale.
      this.lastSeenSequence = msg.sequence;
    } else if (msg.type === "projection.snapshot") {
      // The snapshot is the fresh baseline after a (re)connect; the server
      // may restart its sequence counter, so the watermark restarts too.
      this.lastSeenSequence = -1;
    }
    this.options.onServerMessage(msg);
  }

  private handleClose(ws: WebSocketLike): void {
    if (this.ws !== ws) return;
    this.ws = null;
    this.setConnectionState("closed");
    if (!this.manuallyClosed) {
      this.scheduleReconnect();
    }
  }

  /** Exponential backoff 500ms → 8s cap; resets to 500ms on open. */
  private scheduleReconnect(): void {
    if (this.manuallyClosed || this.retryTimer !== null || this.ws !== null) return;
    const delay = this.backoffMs;
    this.backoffMs = Math.min(this.backoffMs * 2, MAX_BACKOFF_MS);
    this.retryTimer = setTimeout(() => {
      this.retryTimer = null;
      this.openSocket();
    }, delay);
  }

  private setConnectionState(next: ConnectionState): void {
    if (this.state === next) return;
    this.state = next;
    this.options.onConnectionChange(next);
  }

  private settleConnect(): void {
    if (this.resolveConnect !== null) {
      const resolve = this.resolveConnect;
      this.resolveConnect = null;
      this.connectPromise = null;
      resolve();
    }
  }

  private readyMessage(): ClientMessage {
    return {
      type: "client.ready",
      capabilities: {
        audioWorklet:
          typeof AudioContext !== "undefined" &&
          typeof AudioContext.prototype.createAudioWorkletNode === "function",
        indexedDb: typeof indexedDB !== "undefined",
      },
    };
  }
}
